name: swipe_app
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_qr_bar_scanner: ^1.0.2
  scan_preview: ^1.0.2
  fl_chart: ^0.11.0
  charts_flutter: ^0.9.0
  material_design_icons_flutter: ^4.0.5345
  qrcode: ^1.0.4
  font_awesome_flutter: ^8.8.1
  fluttertoast: ^6.0.1
  currency_textfield: ^1.0.3
  intl: ^0.16.1
  shared_preferences: ^0.5.8
  flutter_keyboard_visibility: ^2.0.0
  i18n: ^0.9.12
  build: ^1.3.0
  dio: ^3.0.8
  flutter_mobx: ^1.0.1
  mobx: ^1.2.1+1
  flutter_modular: ^2.0.0+1
  flutter:
    sdk: flutter
  flutter_svg: ^0.18.0
  flare_flutter: ^2.0.1
  flutter_spinkit: ^4.1.1+1
  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.13.0+1
  mask_text_input_formatter: ^1.0.7
  percent_indicator: ^2.1.1+1
  qr_flutter: ^3.2.0
  barcode_flutter: ^1.1.2
  brasil_fields: ^0.3.0
  cpf_cnpj_validator: ^1.0.5
  image_picker: ^0.6.7
  firebase_storage: ^3.1.3
  swipe_sdk:
    path: ../swipe-sdk-dart-light
  permission_handler: ^5.0.1+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_localizations:
    sdk: flutter
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - secrets.json
    - assets/img/home.png
    - assets/img/logo_swipe.png
    - assets/img/logo_swipe.svg
    - assets/img/successfully_created.svg
    - assets/img/logo_swipe_negativo.png
    - assets/img/cash_in.png
    - assets/img/cash_in.svg
    - assets/animation/logo_animation.flr
    - assets/img/background_home.svg
    - assets/img/background_home.png
    - assets/img/documents_background.svg
    - assets/img/info_photo_document.svg
    - assets/img/info_photo_document.png
    - assets/img/info_photo_with_document.png
    - assets/icons/account.svg
    - assets/icons/bill.svg
    - assets/icons/wallet.svg
    - assets/icons/bank.svg
    - assets/icons/receipt.svg
    - assets/icons/pix.png
    - assets/icons/pix.svg
    - assets/icons/cart.svg
    - assets/icons/contact.svg
    - assets/icons/exchange.svg
    - assets/icons/phone.svg
    - assets/icons/deposit.svg
    - assets/icons/shopping_cart.svg
    - assets/icons/icon_card_deposit.svg
    - assets/img/transfer_p2p_confirmed.png
    - assets/img/transfer_p2p_confirmed.svg
    - assets/img/settings_background.svg
    # - assets/img/account.svg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

scripts:
  build_runner: flutter pub run build_runner watch --delete-conflicting-outputs
  build:apk:release: flutter build apk --build-name=0.1.0 --build-number=1
